language: ruby
rvm:
  - 2.3.1
#cache: bundler
services: mongodb
install:
#  - ./dependencies/install_dependencies.sh n y n n
  - ./tenor_install.sh 2 localhost
#  - cd ns-manager && bundle install --gemfile=Gemfile && cd ../

#env:
#  - TEST_DIR=ns-manager
#  - TEST_DIR=ns-catalogue
#  - TEST_DIR=vnf-catalogue
#  - TEST_DIR=.
script:
#  - gem uninstall json -v 2.0.2
  - cd ns-manager && BUNDLE_GEMFILE=/home/travis/build/jbatalle/TeNOR/ns-manager/Gemfile && bundle update --quiet
  - rspec
  - rake start &
  - cd /home/travis/build/jbatalle/TeNOR
  - cd ns-catalogue && BUNDLE_GEMFILE=/home/travis/build/jbatalle/TeNOR/ns-catalogue/Gemfile && bundle update --quiet
  - rspec
  - rake start &
  - cd /home/travis/build/jbatalle/TeNOR
  - cd nsd-validator && BUNDLE_GEMFILE=/home/travis/build/jbatalle/TeNOR/nsd-validator/Gemfile && bundle update --quiet
  - rspec
  - rake start &
  - cd /home/travis/build/jbatalle/TeNOR
  - cd ns-provisioning && BUNDLE_GEMFILE=/home/travis/build/jbatalle/TeNOR/ns-provisioning/Gemfile && bundle update --quiet
  #- rspec
  - rake start &
  - cd /home/travis/build/jbatalle/TeNOR
  - cd vnf-manager && BUNDLE_GEMFILE=/home/travis/build/jbatalle/TeNOR/vnf-manager/Gemfile && bundle update --quiet
  #- rspec
  - rake start &
  - cd /home/travis/build/jbatalle/TeNOR
  - cd vnf-catalogue && BUNDLE_GEMFILE=/home/travis/build/jbatalle/TeNOR/vnf-catalogue/Gemfile && bundle update --quiet
  - rspec
  - rake start &
  - cd /home/travis/build/jbatalle/TeNOR
  - cd vnfd-validator && BUNDLE_GEMFILE=/home/travis/build/jbatalle/TeNOR/vnfd-validator/Gemfile && bundle update --quiet
  - rspec
  - rake start &
  - cd /home/travis/build/jbatalle/TeNOR
  - cd vnf-provisioning && BUNDLE_GEMFILE=/home/travis/build/jbatalle/TeNOR/vnf-provisioning/Gemfile && bundle update --quiet
  #- rspec
  - rake start &
  - cd /home/travis/build/jbatalle/TeNOR
  - cd hot-generator && BUNDLE_GEMFILE=/home/travis/build/jbatalle/TeNOR/hot-generator/Gemfile && bundle update --quiet
  - rspec
  - rake start &
  - cd /home/travis/build/jbatalle/TeNOR
  - sleep 10
  - sleep 20
  - curl localhost:4000/
  - curl localhost:4000/network-services
  - curl localhost:4569/vnfs
  - ./tenor_install.sh 6
  - curl localhost:4000/network-services
  - curl localhost:4000/vnfs
  - curl localhost:4000/ns-instances
#execute end-to-end test
